[tool.poetry]
name = "aipc-agent"
version = "0.1.0"
description = ""
authors = ["Lucky <175917645@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
